/**
 * 실제 거래처 및 제품 데이터
 */

import type { Customer, Product, ProductCategory } from './types';

/**
 * 거래처 목록
 * 
 * 별칭 지원: '//' 로 구분된 이름들은 모두 동일한 거래처를 의미
 * 예: "켈리케이(Kelly.K) // 7조" → '켈리', '7조' 모두 검색 가능
 */
export const CUSTOMERS: Customer[] = [
  { id: '1', name: '경일', aliases: [] },
  { id: '2', name: '고려', aliases: [] },
  { id: '3', name: '고운실', aliases: [] },
  { id: '4', name: '광명', aliases: [] },
  { id: '5', name: '광희', aliases: [] },
  { id: '6', name: '국제', aliases: [] },
  { id: '7', name: '김정임', aliases: [] },
  { id: '8', name: '꼼꼼이', aliases: [] },
  { id: '9', name: '나무사', aliases: [] },
  { id: '10', name: '니트채널', aliases: [] },
  { id: '11', name: '다정', aliases: [] },
  { id: '12', name: '단옥', aliases: [] },
  { id: '13', name: '대영', aliases: [] },
  { id: '14', name: '대천', aliases: [] },
  { id: '15', name: '대풍', aliases: [] },
  { id: '16', name: '덕윤모사', aliases: [] },
  { id: '17', name: '도원', aliases: [] },
  { id: '18', name: '동신', aliases: [] },
  { id: '19', name: '뜨개세상', aliases: [] },
  { id: '20', name: '뜨개퀸', aliases: [] },
  { id: '21', name: '라성', aliases: [] },
  { id: '22', name: '무등2', aliases: [] },
  { id: '23', name: '보성', aliases: [] },
  { id: '24', name: '부전모사', aliases: [] },
  { id: '25', name: '사람과뜨개', aliases: [] },
  { id: '26', name: '사랑', aliases: [] },
  { id: '27', name: '삼성모사', aliases: [] },
  { id: '28', name: '삼성토탈', aliases: [] },
  { id: '29', name: '삼흥', aliases: [] },
  { id: '30', name: '새신랑', aliases: [] },
  { id: '31', name: '서울모사', aliases: [] },
  { id: '32', name: '성남섬유', aliases: [] },
  { id: '33', name: '세림섬유', aliases: [] },
  { id: '34', name: '소망', aliases: [] },
  { id: '35', name: '수성', aliases: [] },
  { id: '36', name: '수아네', aliases: [] },
  { id: '37', name: '수야네', aliases: [] },
  { id: '38', name: '수연', aliases: [] },
  { id: '39', name: '수유시장', aliases: [] },
  { id: '40', name: '스토리얀', aliases: [] },
  { id: '41', name: '승진모사', aliases: [] },
  { id: '42', name: '신동아', aliases: [] },
  { id: '43', name: '신세계', aliases: [] },
  { id: '44', name: '신우모사', aliases: [] },
  { id: '45', name: '신진모사', aliases: [] },
  { id: '46', name: '실바구니', aliases: ['정읍사'] },
  { id: '47', name: '실바람', aliases: [] },
  { id: '48', name: '실방구리', aliases: [] },
  { id: '49', name: '실이야기', aliases: [] },
  { id: '50', name: '썬니트', aliases: [] },
  { id: '51', name: '썬모사', aliases: [] },
  { id: '52', name: '썬텍스', aliases: [] },
  { id: '53', name: '아라상사', aliases: [] },
  { id: '54', name: '야실야실', aliases: [] },
  { id: '55', name: '엄마손', aliases: [] },
  { id: '56', name: '연애사', aliases: [] },
  { id: '57', name: '영화모사', aliases: [] },
  { id: '58', name: '예림', aliases: [] },
  { id: '59', name: '우리', aliases: [] },
  { id: '60', name: '원앙', aliases: [] },
  { id: '61', name: '위빙', aliases: [] },
  { id: '62', name: '유일', aliases: [] },
  { id: '63', name: '유진', aliases: [] },
  { id: '64', name: '장미모사', aliases: [] },
  { id: '65', name: '정감', aliases: [] },
  { id: '66', name: '정신사', aliases: [] },
  { id: '67', name: '조은벗', aliases: [] },
  { id: '68', name: '주식회사 썸유', aliases: [] },
  { id: '69', name: '주식회사 쎄비', aliases: [] },
  { id: '70', name: '㈜앵콜스', aliases: [] },
  { id: '71', name: '㈜필립섬유', aliases: [] },
  { id: '72', name: '진성상사', aliases: [] },
  { id: '73', name: '진양모사', aliases: [] },
  { id: '74', name: '진주', aliases: [] },
  { id: '75', name: '창조', aliases: [] },
  { id: '76', name: '청아', aliases: [] },
  { id: '77', name: '켈리케이(Kelly.K)', aliases: ['7조'] },
  { id: '78', name: '크로바', aliases: [] },
  { id: '79', name: '태광섬유', aliases: ['호남사'] },
  { id: '80', name: '태흥상회', aliases: [] },
  { id: '81', name: '털실나라', aliases: [] },
  { id: '82', name: '파콩', aliases: [] },
  { id: '83', name: '패션메이드', aliases: [] },
  { id: '84', name: '하나상사', aliases: [] },
  { id: '85', name: '한양', aliases: [] },
  { id: '86', name: '한올', aliases: [] },
  { id: '87', name: '한일모사', aliases: [] },
  { id: '88', name: '해비치', aliases: [] },
  { id: '89', name: '현진사', aliases: [] },
  { id: '90', name: '형제섬유', aliases: [] },
  { id: '91', name: '혜성', aliases: [] },
  { id: '92', name: '혜원', aliases: [] },
];

/**
 * 제품 카테고리
 */
export const PRODUCT_CATEGORIES: ProductCategory[] = [
  { id: 'summer', name: '여름실', order: 1 },
  { id: 'winter', name: '겨울실', order: 2 },
  { id: 'accessories', name: '부자재', order: 3 },
];

/**
 * 제품 목록
 */
export const PRODUCTS: Product[] = [
  // 여름실
  { id: 'p1', name: '12합 무지', category: 'summer', aliases: [] },
  { id: 'p2', name: '18합, 무지', category: 'summer', aliases: [] },
  { id: 'p3', name: '24합, 무지', category: 'summer', aliases: [] },
  { id: 'p4', name: '인견', category: 'summer', aliases: [] },
  { id: 'p5', name: '무지Set', category: 'summer', aliases: [] },
  { id: 'p6', name: '18색사', category: 'summer', aliases: [] },
  { id: 'p7', name: '24색사', category: 'summer', aliases: [] },
  { id: 'p8', name: '24B A/B, 24복합', category: 'summer', aliases: [] },
  { id: 'p9', name: '프라하', category: 'summer', aliases: [] },
  { id: 'p10', name: '코스모스', category: 'summer', aliases: [] },
  { id: 'p11', name: '코스_미니', category: 'summer', aliases: [] },
  { id: 'p12', name: '코스_미니세트', category: 'summer', aliases: [] },
  { id: 'p13', name: '자연', category: 'summer', aliases: [] },
  { id: 'p14', name: '체이니얀', category: 'summer', aliases: [] },
  { id: 'p15', name: '체이니_플러스얀', category: 'summer', aliases: [] },
  { id: 'p16', name: 'xx레이스(라키)', category: 'summer', aliases: [] },
  { id: 'p17', name: '아몬드', category: 'summer', aliases: [] },
  { id: 'p18', name: '클라우드', category: 'summer', aliases: [] },
  { id: 'p19', name: '인형나라, AC', category: 'summer', aliases: [] },
  { id: 'p20', name: '인형나라 _set', category: 'summer', aliases: [] },
  { id: 'p21', name: '골드바틱', category: 'summer', aliases: [] },
  { id: 'p22', name: '깨끗한 수세미', category: 'summer', aliases: [] },
  { id: 'p23', name: '당근', category: 'summer', aliases: [] },
  { id: 'p24', name: '디바', category: 'summer', aliases: [] },
  { id: 'p25', name: '디바_옴브레', category: 'summer', aliases: [] },
  { id: 'p26', name: '디바바틱', category: 'summer', aliases: [] },
  { id: 'p27', name: '로코코', category: 'summer', aliases: [] },
  { id: 'p28', name: '매직파트너', category: 'summer', aliases: [] },
  { id: 'p29', name: '미스바틱', category: 'summer', aliases: [] },
  { id: 'p30', name: '바하바틱', category: 'summer', aliases: [] },
  { id: 'p31', name: '반딧불', category: 'summer', aliases: [] },
  { id: 'p32', name: '베테랑', category: 'summer', aliases: [] },
  { id: 'p33', name: '벨라_옴브레', category: 'summer', aliases: [] },
  { id: 'p34', name: '소담', category: 'summer', aliases: [] },
  { id: 'p35', name: '스파클', category: 'summer', aliases: [] },
  { id: 'p36', name: '실크로드', category: 'summer', aliases: [] },
  { id: 'p37', name: '엑스트라', category: 'summer', aliases: [] },
  { id: 'p38', name: '오로라케이팝, 오로라메탈', category: 'summer', aliases: [] },
  { id: 'p39', name: '웰빙 수세미', category: 'summer', aliases: [] },
  { id: 'p40', name: '캔디토핑', category: 'summer', aliases: [] },
  { id: 'p41', name: '케이크 얀', category: 'summer', aliases: [] },
  { id: 'p42', name: '케이팝, 메탈', category: 'summer', aliases: [] },
  { id: 'p43', name: '코튼퀸', category: 'summer', aliases: [] },
  { id: 'p44', name: '피크닉', category: 'summer', aliases: [] },
  { id: 'p45', name: '해맑수, 해맑은 수세미', category: 'summer', aliases: [] },

  // 겨울실
  { id: 'p46', name: '래빗', category: 'winter', aliases: [] },
  { id: 'p47', name: '래빗_b', category: 'winter', aliases: [] },
  { id: 'p48', name: '맥시', category: 'winter', aliases: [] },
  { id: 'p49', name: '맥시_B', category: 'winter', aliases: [] },
  { id: 'p50', name: '맥시_롱바틱', category: 'winter', aliases: [] },
  { id: 'p51', name: '메가필', category: 'winter', aliases: [] },
  { id: 'p52', name: '클라식', category: 'winter', aliases: [] },
  { id: 'p53', name: '자이언트울', category: 'winter', aliases: [] },
  { id: 'p54', name: '몬스타', category: 'winter', aliases: [] },
  { id: 'p55', name: '버디', category: 'winter', aliases: [] },
  { id: 'p56', name: '베로나', category: 'winter', aliases: [] },
  { id: 'p57', name: '부르쿰바틱', category: 'winter', aliases: [] },
  { id: 'p58', name: '살아비에', category: 'winter', aliases: [] },
  { id: 'p59', name: '슈퍼앙고라1000', category: 'winter', aliases: [] },
  { id: 'p60', name: '아티산', category: 'winter', aliases: [] },
  { id: 'p61', name: '알파카2000', category: 'winter', aliases: [] },
  { id: 'p62', name: '앙고라_그라데이션, 앙그라', category: 'winter', aliases: [] },
  { id: 'p63', name: '앙고라_심', category: 'winter', aliases: [] },
  { id: 'p64', name: '앙고라골드', category: 'winter', aliases: [] },
  { id: 'p65', name: '울에이스', category: 'winter', aliases: [] },
  { id: 'p66', name: '첼로', category: 'winter', aliases: [] },
  { id: 'p67', name: '트위드', category: 'winter', aliases: [] },
  { id: 'p68', name: '퍼피모어', category: 'winter', aliases: [] },
  { id: 'p69', name: '퍼피파인', category: 'winter', aliases: [] },
  { id: 'p70', name: '나나골드', category: 'winter', aliases: [] },

  // 부자재
  { id: 'p71', name: '실리콘코', category: 'accessories', aliases: [] },
  { id: 'p72', name: '실리콘 대', category: 'accessories', aliases: [] },
  { id: 'p73', name: '실리콘세트', category: 'accessories', aliases: [] },
  { id: 'p74', name: '대나무코바늘, 대코', category: 'accessories', aliases: [] },
  { id: 'p75', name: '줄중(2.5~5.0mm)', category: 'accessories', aliases: [] },
  { id: 'p76', name: '줄대(5.5~8.0mm)', category: 'accessories', aliases: [] },
  { id: 'p77', name: '줄특(9.0~12mm)', category: 'accessories', aliases: [] },
  { id: 'p78', name: '줄중목40cm(2.5~5.0mm)', category: 'accessories', aliases: [] },
  { id: 'p79', name: '줄대목40cm(5.5~8.0mm)', category: 'accessories', aliases: [] },
  { id: 'p80', name: '줄특목40cm(9.0~12mm)', category: 'accessories', aliases: [] },
  { id: 'p81', name: '줄15m', category: 'accessories', aliases: [] },
  { id: 'p82', name: '줄20m', category: 'accessories', aliases: [] },
  { id: 'p83', name: '줄25m', category: 'accessories', aliases: [] },
  { id: 'p84', name: '아디낱', category: 'accessories', aliases: [] },
  { id: 'p85', name: '아디대낱', category: 'accessories', aliases: [] },
  { id: 'p86', name: '아디8', category: 'accessories', aliases: [] },
  { id: 'p87', name: '아디set', category: 'accessories', aliases: [] },
  { id: 'p88', name: '아디대set', category: 'accessories', aliases: [] },
  { id: 'p89', name: '아디8set', category: 'accessories', aliases: [] },
  { id: 'p90', name: '아디 단수링', category: 'accessories', aliases: [] },
  { id: 'p91', name: '아크릴방울', category: 'accessories', aliases: [] },
  { id: 'p92', name: '여우방울', category: 'accessories', aliases: [] },
  { id: 'p93', name: '장갑바늘', category: 'accessories', aliases: [] },
  { id: 'p94', name: '히트줄', category: 'accessories', aliases: [] },
  { id: 'p95', name: '히트줄_set', category: 'accessories', aliases: [] },
  { id: 'p96', name: 'pvc보석코', category: 'accessories', aliases: [] },
  { id: 'p97', name: '국산코_골드', category: 'accessories', aliases: [] },
  { id: 'p98', name: '국산코_은색', category: 'accessories', aliases: [] },
  { id: 'p99', name: '꽈베기_미니', category: 'accessories', aliases: [] },
  { id: 'p100', name: '꽈베기_중(대)', category: 'accessories', aliases: [] },
  { id: 'p101', name: '꽈베기_대', category: 'accessories', aliases: [] },
  { id: 'p102', name: '꽈베기_특', category: 'accessories', aliases: [] },
  { id: 'p103', name: '꽈베기set', category: 'accessories', aliases: [] },
  { id: 'p104', name: '돗바늘', category: 'accessories', aliases: [] },
  { id: 'p105', name: '나무 돗바늘', category: 'accessories', aliases: [] },
  { id: 'p106', name: '나무코10,12', category: 'accessories', aliases: [] },
  { id: 'p107', name: '나무코10,12_set', category: 'accessories', aliases: [] },
  { id: 'p108', name: '나무코15', category: 'accessories', aliases: [] },
  { id: 'p109', name: '나무코20', category: 'accessories', aliases: [] },
  { id: 'p110', name: '단수링', category: 'accessories', aliases: [] },
  { id: 'p111', name: '단숫자', category: 'accessories', aliases: [] },
  { id: 'p112', name: '막대긴바늘12', category: 'accessories', aliases: [] },
  { id: 'p113', name: '막대긴바늘15', category: 'accessories', aliases: [] },
  { id: 'p114', name: '머리끈', category: 'accessories', aliases: [] },
  { id: 'p115', name: '실리콘코_양쪽', category: 'accessories', aliases: [] },
  { id: 'p116', name: '아기여우인형', category: 'accessories', aliases: [] },
  { id: 'p117', name: '아기요정인형', category: 'accessories', aliases: [] },
  { id: 'p118', name: '알루 코바늘', category: 'accessories', aliases: [] },
  { id: 'p119', name: '알루_코바늘', category: 'accessories', aliases: [] },
  { id: 'p120', name: '어깨핀_대', category: 'accessories', aliases: [] },
  { id: 'p121', name: '어깨핀_미니', category: 'accessories', aliases: [] },
  { id: 'p122', name: '어깨핀_중(대)', category: 'accessories', aliases: [] },
  { id: 'p123', name: '어깨핀_특', category: 'accessories', aliases: [] },
  { id: 'p124', name: '어깨핀set', category: 'accessories', aliases: [] },
  { id: 'p125', name: '진주머리끈', category: 'accessories', aliases: [] },
  { id: 'p126', name: '커팅 목걸이', category: 'accessories', aliases: [] },
];
